# Aliyun Access Key
[credentials]
access_key_id = "your_access_key_id"
access_key_secret = "your_access_key_secret"

# Domain Settings
# Format: interface_name = "domain_name"
# [[domains]]
# domain_name = "your_domain_name"
# bind_interface = "enp4s0" #
# type = "AAAA"
# subdomain = ["@", "*", "www"]
